// AUTH
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';
export const ACTIVATION_SUCCESS = 'ACTIVATION_SUCCESS';
export const ACTIVATION_FAIL = 'ACTIVATION_FAIL';
export const USER_LOADED_SUCCESS = 'USER_LOADED_SUCCESS';
export const USER_LOADED_FAIL = 'USER_LOADED_FAIL';
export const AUTHENTICATED_SUCCESS = 'AUTHENTICATED_SUCCESS';
export const AUTHENTICATED_FAIL = 'AUTHENTICATED_FAIL';
export const PASSWORD_RESET_FAIL = 'PASSWORD_RESET_FAIL';
export const PASSWORD_RESET_SUCCESS = 'PASSWORD_RESET_SUCCESS';
export const PASSWORD_RESET_CONFIRM_FAIL = 'PASSWORD_RESET_CONFIRM_FAIL';
export const PASSWORD_RESET_CONFIRM_SUCCESS = 'PASSWORD_RESET_CONFIRM_SUCCESS';
export const GOOGLE_AUTH_SUCCESS = 'GOOGLE_AUTH_SUCCESS';
export const GOOGLE_AUTH_FAIL = 'GOOGLE_AUTH_FAIL';
export const FACEBOOK_AUTH_SUCCESS = 'FACEBOOK_AUTH_SUCCESS';
export const FACEBOOK_AUTH_FAIL = 'FACEBOOK_AUTH_FAIL';
export const LOGOUT = 'LOGOUT';

// personal profile
export const CREATE_PERSONAL_PROFILE_SUCCESS = 'CREATE_PERSONAL_PROFILE_SUCCESS';
export const CREATE_PERSONAL_PROFILE_FAIL = 'CREATE_PERSONAL_PROFILE_FAIL';
export const FETCH_PERSONAL_PROFILE_SUCCESS = 'FETCH_PERSONAL_PROFILE_SUCCESS';
export const FETCH_PERSONAL_PROFILE_FAIL = 'FETCH_PERSONAL_PROFILE_FAIL';
export const GET_SINGLE_PERSONAL_PROFILE_SUCCESS = 'GET_PERSONAL_PROFILE_SUCCESS';
export const GET_SINGLE_PERSONAL_PROFILE_FAIL = 'GET_PERSONAL_PROFILE_FAIL';
export const UPDATE_PERSONAL_PROFILE_SUCCESS = 'UPDATE_PERSONAL_PROFILE_SUCCESS';
export const UPDATE_PERSONAL_PROFILE_FAIL = 'UPDATE_PERSONAL_PROFILE_FAIL';

// company profile
export const UPDATE_COMPANY_PROFILE_SUCCESS = 'UPDATE_COMPANY_PROFILE_SUCCESS';
export const UPDATE_COMPANY_PROFILE_FAIL = 'UPDATE_COMPANY_PROFILE_FAIL';
export const CREATE_COMPANY_PROFILE_SUCCESS = 'CREATE_COMPANY_PROFILE_SUCCESS';
export const CREATE_COMPANY_PROFILE_FAIL = 'CREATE_COMPANY_PROFILE_FAIL';
export const FETCH_COMPANY_PROFILE_SUCCESS = 'FETCH_COMPANY_PROFILE_SUCCESS';
export const FETCH_COMPANY_PROFILE_FAIL = 'FETCH_COMPANY_PROFILE_FAIL';

export const EDIT_PROFILE_SUCCESS = 'EDIT_PROFILE_SUCCESS'
export const EDIT_PROFILE_ERROR = 'EDIT_PROFILE_ERROR'


// SETTINGS
export const TOGGLE_COLLAPSED_NAV = 'TOGGLE_COLLAPSE_MENU';
export const DRAWER_TYPE = 'DRAWER_TYPE';
export const FIXED_DRAWER = 'FIXED_DRAWER';
export const COLLAPSED_DRAWER = 'COLLAPSIBLE';
export const WINDOW_WIDTH = 'WINDOW-WIDTH';

// MESSAGE
export const SHOW_SUCCESS_MESSAGE = 'SHOW_SUCCESS_MESSAGE';
export const SHOW_ERROR_MESSAGE = 'SHOW_ERROR_MESSAGE';
export const HIDE_MESSAGE = 'HIDE_MESSAGE';


// DASHBOARD
export const SHOW_SIDEBAR = 'SHOW_SIDEBAR'
export const LOADING = 'LOADING';
export const OFF_LOADING = 'OFF_LOADING';


// FUND RAISE & DONATE
export const CREATE_FUND_CASH_SUCCESS = 'CREATE_FUND_CASH_SUCCESS';
export const CREATE_FUND_CASH_FAIL= ' CREATE_FUND_CASH_FAIL';
export const UPDATE_FUND_CASH_SUCCESS = 'UPDATE_FUND_CASH_SUCCESS';
export const UPDATE_FUND_CASH_FAIL= ' UPDATE_FUND_CASH_FAIL';
export const DELETE_FUND_CASH_SUCCESS = 'DELETE_FUND_CASH_SUCCESS';
export const DELETE_FUND_CASH_FAIL= ' DELETE_FUND_CASH_FAIL';
export const FETCH_FUND_CASH_SUCCESS= ' FETCH_FUND_CASH_SUCCESS';
export const FETCH_FUND_CASH_FAIL= ' FETCH_FUND_CASH_FAIL';

export const CREATE_FUND_ITEM_SUCCESS = 'CREATE_FUND_ITEM_SUCCESS';
export const CREATE_FUND_ITEM_FAIL= ' CREATE_FUND_ITEM_FAIL';
export const UPDATE_FUND_ITEM_SUCCESS = 'UPDATE_FUND_ITEM_SUCCESS';
export const UPDATE_FUND_ITEM_FAIL= ' UPDATE_FUND_ITEM_FAIL';
export const DELETE_FUND_ITEM_SUCCESS = 'DELETE_FUND_ITEM_SUCCESS';
export const DELETE_FUND_ITEM_FAIL= ' DELETE_FUND_ITEM_FAIL';
export const FETCH_FUND_ITEM_SUCCESS= ' FETCH_FUND_ITEM_SUCCESS';
export const FETCH_FUND_ITEM_FAIL= ' FETCH_FUND_ITEM_FAIL';


export const CREATE_DONATION_CASH_SUCCESS = 'CREATE_DONATION_CASH_SUCCESS';
export const CREATE_DONATION_CASH_FAIL= ' CREATE_DONATION_CASH_FAIL';
export const UPDATE_DONATION_CASH_SUCCESS = 'UPDATE_DONATION_CASH_SUCCESS';
export const UPDATE_DONATION_CASH_FAIL= ' UPDATE_DONATION_CASH_FAIL';
export const DELETE_DONATION_CASH_SUCCESS = 'DELETE_DONATION_CASH_SUCCESS';
export const DELETE_DONATION_CASH_FAIL= ' DELETE_DONATION_CASH_FAIL';
export const FETCH_DONATION_CASH_SUCCESS= ' FETCH_DONATION_CASH_SUCCESS';
export const FETCH_DONATION_CASH_FAIL= ' FETCH_DONATION_CASH_FAIL';


export const CREATE_DONATION_ITEM_SUCCESS = 'CREATE_DONATION_ITEM_SUCCESS';
export const CREATE_DONATION_ITEM_FAIL= ' CREATE_DONATION_ITEM_FAIL';
export const UPDATE_DONATION_ITEM_SUCCESS = 'UPDATE_DONATION_ITEM_SUCCESS';
export const UPDATE_DONATION_ITEM_FAIL= ' UPDATE_DONATION_ITEM_FAIL';
export const DELETE_DONATION_ITEM_SUCCESS = 'DELETE_DONATION_ITEM_SUCCESS';
export const DELETE_DONATION_ITEM_FAIL= ' DELETE_DONATION_ITEM_FAIL';
export const FETCH_DONATION_ITEM_SUCCESS= ' FETCH_DONATION_ITEM_SUCCESS';
export const FETCH_DONATION_ITEM_FAIL= ' FETCH_DONATION_ITEM_FAIL';

export const CREATE_DONATION_ITEMSELL_SUCCESS = 'CREATE_DONATION_ITEMSELL_SUCCESS';
export const CREATE_DONATION_ITEMSELL_FAIL= 'CREATE_DONATION_ITEMSELL_FAIL';
export const UPDATE_DONATION_ITEMSELL_SUCCESS = 'UPDATE_DONATION_ITEMSELL_SUCCESS';
export const UPDATE_DONATION_ITEMSELL_FAIL= 'UPDATE_DONATION_ITEMSELL_FAIL';
export const DELETE_DONATION_ITEMSELL_SUCCESS = 'DELETE_DONATION_ITEMSELL_SUCCESS';
export const DELETE_DONATION_ITEMSELL_FAIL= 'DELETE_DONATION_ITEMSELL_FAIL';
export const FETCH_DONATION_ITEMSELL_SUCCESS= 'FETCH_DONATION_ITEMSELL_SUCCESS';
export const FETCH_DONATION_ITEMSELL_FAIL= ' FETCH_DONATION_ITEMSELL_FAIL';

// fetch campagns and single
export const GET_ALL_CAMPAIGN_FAIL = 'GET_ALL_CAMPAING_FAIL';
export const GET_ALL_CAMPAIGN_SUCCESS = 'GET_ALL_CAMPAING_SUCCESS';
export const GET_SINGLE_CAMPAIGN_SUCCESS = 'GET_SINGLE_CAMPAIGN_SUCCESS'
export const GET_SINGLE_CAMPAIGN_FAIL = 'GET_SINGLE_CAMPAIGN_FAIL'



export const CREATE_CASH_DONATION_OGAFUND_SUCCESS = 'CREATE_CASH_DONATION_OGAFUND_SUCCESS'
export const CREATE_CASH_DONATION_OGAFUND_FAIL = 'CREATE_CASH_DONATION_OGAFUND_FAIL'
export const UPDATE_CASH_DONATION_OGAFUND_SUCCESS = 'UPDATE_CASH_DONATION_OGAFUND_SUCCESS'
export const DELETE_CASH_DONATION_OGAFUND_SUCCESS = 'DELETE_CASH_DONATION_OGAFUND_SUCCESS'
export const GET_CASH_DONATION_OGAFUND_SUCCESS =  'GET_DONATION_CASH_OGAFUND_SUCCESS'

export const CREATE_ITEM_DONATION_OGAFUND_SUCCESS = 'CREATE_ITEM_DONATION_OGAFUND_SUCCESS'
export const CREATE_ITEM_DONATION_OGAFUND_FAIL = 'CREATE_ITEM_DONATION_OGAFUND_FAIL'
export const UPDATE_ITEM_DONATION_OGAFUND_SUCCESS = 'UPDATE_ITEM_DONATION_OGAFUND_SUCCESS'
export const DELETE_ITEM_DONATION_OGAFUND_SUCCESS = 'DELETE_ITEM_DONATION_OGAFUND_SUCCESS'
export const GET_ITEM_DONATION_OGAFUND_SUCCESS =  'GET_ITEM_DONATION_OGAFUND_SUCCESS'

export const GET_USER_DONATIONS_RECEIVED = "GET_USER_DONATIONS_RECEIVED"
export const GET_USER_DONATIONS_FAILED = "GET_USER_DONATIONS_FAILED"


// category
export const FUND_RAISE_BUTTON_CLICKED = 'FUND_RAISE_BUTTON_CLICKED'
export const FUND_RAISE_CATEGORIES = 'FUND_RAISE_CATEGORIES'

// cart
export const TOGGLE_CART_HIDDEN = 'TOGGLE_CART_HIDDEN'
export const CART_HIDDEN = 'CART_HIDDEN'
export const ADD_ITEM = 'ADD_ITEM'
export const CLEAR_ITEM_FROM_CART = 'CLEAR_ITEM_FROM_CART'
export const CLEAR_CART = 'CLEAR_CART'
export const REMOVE_ITEM = 'REMOVE_ITEM'
export const VERIFY_PAYSTACK = 'VERIIFY_PAYSTACK'


//market place
export const UPDATE_MARKET_COLLECTIONS = 'UPDATE_MARKET_COLLECTIONS'
export const UPDATE_MARKET_COLLECTIONS_FAIL = 'UPDATE_MARKET_COLLECTIONS_FAIL'

export const GET_SINGLE_MARKET_COLLECTIONS_SUCCESS = 'GET_SINGLE_MARKET_COLLECTIONS_SUCCESS'
export const GET_SINGLE_MARKET_COLLECTIONS_FAIL = 'GET_SINGLE_MARKET_COLLECTIONS_FAIL'

// TOGGLE DASHBOARD SIDENAV
export const TOGGLE_DASHBOARD_SIDENAV = 'TOGGLE_DASHBOARD_SIDENAV'
export const TOGGLE_DASHBOARD_MOBILE_SIDENAV = 'TOGGLE_DASHBOARD_MOBILE_SIDENAV'


// shipping address
export const CREATE_SHIPPING_ADDRESS_SUCCESS = 'CREATE_SHIPPING_ADDRESS_SUCCESS';
export const CREATE_SHIPPING_ADDRESS_FAIL = 'CREATE_SHIPPING_ADDRESS_FAIL';
export const UPDATE_SHIPPING_ADDRESS_SUCCESS = 'UPDATE_SHIPPING_ADDRESS_SUCCESS';
export const UPDATE_SHIPPING_ADDRESS_FAIL = 'UPDATE_SHIPPING_ADDRESS_FAIL';
export const FETCH_SHIPPING_ADDRESS_SUCCESS = 'FETCH_SHIPPING_ADDRESS_SUCCESS';
export const FETCH_SHIPPING_ADDRESS_FAIL = 'FETCH_SHIPPING_ADDRESS_FAIL';
export const GET_SINGLE_SHIPPING_ADDRESS_SUCCESS = 'GET_SINGLE_SHIPPING_ADDRESS_SUCCESS';
export const GET_SINGLE_SHIPPING_ADDRESS_FAIL = 'GET_SINGLE_SHIPPING_ADDRESS_FAIL';
export const SHOW_FORM = 'SHOW_FORM';

// ORDERS
export const PLACE_ORDERS_PAYSTACK_SUCCESS = 'PLACE_ORDERS_PAYSTACK_SUCCESS';
export const PLACE_ORDERS_PAYSTACK_CLEAR = 'PLACE_ORDERS_PAYSTACK_CLEAR';
export const PLACE_ORDERS_PAYSTACK_FAIL = 'PLACE_ORDERS_PAYSTACK_FAIL';
export const PLACE_ORDERS_STRIPE_SUCCESS = 'PLACE_ORDERS_STRIPE_SUCCESS';
export const PLACE_ORDERS_STRIPE_FAIL = 'PLACE_ORDERS_STRIPE_FAIL';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS'
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL'

// AUCTION
export const CREATE_AUCTION_SUCCESS = "CREATE_AUCTION_SUCCESS";
export const FETCH_AUCTION_SUCCESS = "FETCH_AUCTION_SUCCESS";
export const CREATE_AUCTION_FAIL = "CREATE_AUCTION_FAIL";
export const FETCH_AUCTION_FAIL = "FETCH_AUCTION_FAIL";

